### ISSUE TITLE
Support React Native 0.67

### ISSUE THREAD

**Issue by frenic** [MindscapeHQ/raygun4reactnative#52]
Gradle is bumped to v7, in React Native 0.67, where [legacy `maven` plugin is removed](https://docs.gradle.org/7.0/userguide/upgrading_version_6.html?_ga=2.21245883.1883799052.1624281891-1948725710.1624281891#removal_of_the_legacy_maven_plugin). This results in this error:

```bash
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\dev\lykoapp\node_modules\raygun4reactnative\android\build.gradle' line: 23

* What went wrong:
A problem occurred evaluating project ':raygun4reactnative'.
> Plugin with id 'maven' not found.
```

**Comment by Widdershin** [comment]
Hi @frenic,

Thanks for the issue report. We've released a fix for this issue as part of v1.2.0, which was released today.

Please let us know if you encounter any other problems 🙂
