### ISSUE TITLE
iOS Exceptions not making it to RayGun

### ISSUE THREAD

**Issue by rkeiii** [MindscapeHQ/raygun4reactnative#66]
We've had two customers report (on 1/6/23) our app starting to open, flashing a white screen, then crashing. These crashes made it into Apple App Store crash data but are not showing up in RayGun. Is this expected behavior if the exceptions occurred to early during init or should RayGun be seeing these?

See the attached sample crash log downloaded from Apple. [samplecrash.txt](https://github.com/MindscapeHQ/raygun4reactnative/files/10369417/samplecrash.txt)

The only place I can see we're deviating from the install instructions is in our PodFile. We're using a newer SDK version. Is this a problem? `platform :ios, '12.4'`

**Comment by miquelbeltran** [comment]
> Is this expected behavior if the exceptions occurred to early during init or should RayGun be seeing these?

raygun4reactnative does use internally the raygun4apple package and the error should be captured by it. So yes, this is not expected behavior.

**Comment by miquelbeltran** [comment]
Hi again, we added some clarification regarding capturing native errors on the README, I hope that helps.
