### ISSUE TITLE
NullPointerException when `customData` is undefined

### ISSUE THREAD

**Issue by frenic** [MindscapeHQ/raygun4reactnative#67]
We noticed that we get a `java.lang.NullPointerException` in `com.raygun.react.RaygunNativeBridgeModule.recordBreadcrumb` when `breadcrumb.customData` is undefined. E.g:

```ts
const customData;

RaygunClient.recordBreadcrumb({
  message: 'My breadcrumb',
  customData,
});

**Comment by redJ4y** [comment]
I added some logic to protect against this for version 1.2.4, thanks for the tip!
