### ISSUE TITLE
Expo support of this package?

### ISSUE THREAD

**Issue by Puneet56** [MindscapeHQ/raygun4reactnative#70]
Hi does this package also supports expo for react native. If not, is there any other package that I should use?
I tried installing this package in expo app and faced this error.

 ERROR  TypeError: undefined is not an object (evaluating '_raygun4reactnative.RaygunClient.init')

This error is located at:
    in App (created by withDevTools(App))
    in withDevTools(App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)

![image](https://user-images.githubusercontent.com/26213419/218434181-1282f9d4-2e01-4903-95b6-804fe024b62d.png)

**Comment by miquelbeltran** [comment]
Hello! Sorry that this message has been unanswered for a long time, but I have added a guide to use this Raygun provider on Expo, as well as a demo project under `ExpoDemo`. I hope that can help to anyone looking to use the provider in Expo projects.
