### ISSUE TITLE
crash with xcode 16 beta

### ISSUE THREAD

**Issue by alainib** [MindscapeHQ/raygun4reactnative#79]
i use   

"raygun4reactnative": "1.3.0",
"react-native": "0.74.2",

lastest xcode Version 16.0 beta 2 (16A5171r) 

i cannot run my project anymore

i get `No type named 'terminate_handler' in namespace 'std'` errors 

<img width="500" alt="Capture d’écran 2024-07-03 à 14 18 16" src="https://github.com/MindscapeHQ/raygun4reactnative/assets/7910081/a215d590-6779-4ff6-af7a-ca7700fd845e">

<img width="1064" alt="Capture d’écran 2024-07-03 à 14 18 40" src="https://github.com/MindscapeHQ/raygun4reactnative/assets/7910081/e57a2c0a-8d74-4201-962d-f569975ef008">

what can i do ? thanks

**Comment by Pallesen01** [comment]
Hi @alainib, this was an issue with raygun4apple provider and is fixed in the new version [here](https://github.com/MindscapeHQ/raygun4apple/releases/tag/2.1.1). See if updating fixes your issue 🙂

**Comment by alainib** [comment]
> Hi @alainib, this was an issue with raygun4apple provider and is fixed in the new version [here](https://github.com/MindscapeHQ/raygun4apple/releases/tag/2.1.1). See if updating fixes your issue 🙂

hello . 
thanks for help and super fast response :) 

do you plan to update raygun4reactnative package because it's not updated since 8 months . how to get last update for this bug ? thanks

**Comment by Pallesen01** [comment]
Hi, sorry for the delay in getting back to you. An update has just been released for the raygun4reactnative package. Please try updating and let us know if this issue continues.

**Comment by alainib** [comment]
hello @Pallesen01 wow thanks for the new release .
