### ISSUE TITLE
[Android] Cannot read property 'DEVICE_ID' of null

### ISSUE THREAD

**Issue by dziter** [MindscapeHQ/raygun4reactnative#85]
Regarding the last release, v.1.4.4, I get this error on Android devices.
Please note that I have noticed the same issue on v.1.4.2.

```
"raygun4reactnative": "^1.4.4",
"react-native": "0.74.3",
```

Thanks in advance for the quick fix @Pallesen01 

<img width="430" alt="1 4 4" src="https://github.com/user-attachments/assets/f88a8ee3-7bda-4ac0-9827-9bfc90853038">

**Comment by Pallesen01** [comment]
Hi @dziter,

Thanks for the heads up, I'll look at getting a release out to fix this soon 🙂

**Comment by nirodhaperera-ifs** [comment]
Facing similar issue with RaygunNativeBridge module being 'null'. @Pallesen01 any update on this?

**Comment by Pallesen01** [comment]
Hi @nirodhaperera-ifs, we've narrowed down the cause of this issue but are still working on getting a fix out. I'll update here when we get this released.

**Comment by Pallesen01** [comment]
Hi, We've just released [v1.4.5](https://github.com/MindscapeHQ/raygun4reactnative/releases/tag/v.1.4.5) to address this issue. Thanks for reporting this!

**Comment by dziter** [comment]
Perfect, it works on both iOS & Android with release 1.4.5. 
Thanks @Pallesen01
